/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,ts,tsx}',
    './components/**/*.{js,ts,tsx}',
    './screens/**/*.{js,ts,tsx}',
    './navigation/**/*.{js,ts,tsx}',
    './constants/**/*.{js,ts,tsx}',
  ],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#131316',
        surface: '#1f1f22',
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'on-surface': '#e4e1e6',
        'on-surface-variant': '#cfc2d6',
        'inverse-surface': '#e4e1e6',
        'inverse-on-surface': '#303033',
        outline: '#988d9f',
        'outline-variant': '#4d4354',
        'surface-tint': '#e5005c',
        primary: '#e5005c',
        'on-primary': '#ffffff',
        'primary-container': '#ff80ab',
        'on-primary-container': '#4c0028',
        'inverse-primary': '#ffb2c3',
        secondary: '#c8c6c9',
        'on-secondary': '#303033',
        'secondary-container': '#47464a',
        'on-secondary-container': '#b6b4b8',
        tertiary: '#fabc4e',
        'on-tertiary': '#432c00',
        'tertiary-container': '#bd871a',
        'on-tertiary-container': '#3a2600',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        success: '#22c55e',
        warning: '#eab308',
        critical: '#ef4444',
        'text-main': '#fafafa',
        'text-muted': '#a1a1aa',
        'border-subtle': '#3f3f46',
      },
      fontFamily: {
        hanken: ['Hanken Grotesk', 'sans-serif'],
        jetbrains: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
